#define DEVELOPMENT
#ifdef DEVELOPMENT
#define MIN_LEAF_SIZE 32
#define NUM_FEATURES  4
#define NUM_INSTANCES 32*1024
#define BUFSZ  8
#define MIN_PARTITION_SIZE MIN_LEAF_SIZE
#define MAX_NUM_NODES_DT (NUM_INSTANCES / MIN_LEAF_SIZE)
#endif

#undef PERF_TEST
#ifdef PERF_TEST
#define MIN_LEAF_SIZE 128
#define NUM_FEATURES  128
#define NUM_INSTANCES (1024*1024)
#define BUFSZ         4096
#define MIN_PARTITION_SIZE MIN_LEAF_SIZE
// #define MAX_NUM_NODES_DT (NUM_INSTANCES / MIN_LEAF_SIZE)
#define MAX_NUM_NODES_DT 65536
#endif
