/*
#define MIN_LEAF_SIZE 128
#define NUM_FEATURES  128
#define NUM_INSTANCES (1024*1024)
#define BUFSZ         4096
#define MIN_PARTITION_SIZE MIN_LEAF_SIZE
// #define MAX_NUM_NODES_DT (NUM_INSTANCES / MIN_LEAF_SIZE)
#define MAX_NUM_NODES_DT 65536
*/
